#!/usr/bin/env bash

BASE_DIR='/opt/cisco/anyconnect/umbrella'

read -r -d '' USAGE << EGASU
Usage: `basename $0` [-s|-e|-d|-h]

    -s, --status    Print Umbrella Roaming Security module status
    -e, --enable    Enable logging feature
    -d, --disable   Disable logging feature
    -u, --up        Start Umbrella Roaming Module
    -k, --kill      Stop Umbrella Roaming Module
    -r, --restart   Restart Umbrella Roaming Module
    -h, --help      Show this message.
EGASU

# Stop service
function stop_service {
    sudo launchctl unload /Library/LaunchDaemons/com.cisco.anyconnect.vpnagentd.plist
}

# Start service
function start_service {
    sudo launchctl load /Library/LaunchDaemons/com.cisco.anyconnect.vpnagentd.plist
}

# Enable SWG Max debug logging
function enable_swgmaxdebug {
    sudo cat $BASE_DIR/SWG/SWGConfig.json | awk -F "orgConfig\": " '{print $2}' | awk -F ", \"commonConfig" '{print $1}' | sed "s/}/, \"logLevel\": \"1\" }/g" > $BASE_DIR/data/swg_org_config.flag
}

# Disable SWG Max Debug Logging
function disable_swgmaxdebug {
    sudo rm $BASE_DIR/data/swg_org_config.flag 
}

function verify_swgmaxdebug {
    swglogout=$(log show --predicate 'subsystem contains "com.cisco.anyconnect.swg"||senderImagePath endswith "acswgagent"' --debug --info --last 5m)
    if [[ $swglogout == *"Hostnames from KDF are"* ]]; then
        echo "Looks like SWG Max debug logging enabled and we see web redirection events"
    else
        echo "No events available, check if SWG max debug logging is enabled"
    fi    
}

case "$1" in
    '-s'|'--status')
        check_status &&
        echo Umbrella Roaming Security Module for AnyConnect is ENABLED. ||
        echo Umbrella Roaming Security Module for AnyConnect is DISABLED.
        exit 0
        ;;
    '-u'|'--up')
        start_service &&
        echo Umbrella Roaming Security Module for AnyConnect has been STARTED. &&
        exit 0 ||
        echo ERROR: Umbrella Roaming Security Module for AnyConnect can only be enabled if it has previously been disabled by this utility.
        exit 1
        ;;
    '-k'|'--kill')
        stop_service &&
        echo Umbrella Roaming Security Module for AnyConnect has been STOPPED. ||
        echo ERROR: Umbrella Roaming Security Module for AnyConnect does not appear to be enabled.
        exit 1
        ;;
    '-r'|'--restart')
        stop_service &&
        echo Umbrella Roaming Security Module for AnyConnect has been STOPPED. &&
        start_service &&
        echo Umbrella Roaming Security Module for AnyConnect has been STARTED.
        exit 0
        ;;
    '-e'|'--enable')
        case "$2" in
           'swg')
              enable_swgmaxdebug &&
              echo SWG Max debug logging has ENABLED
              exit 1
              ;;
           'kdf')
              echo KDF_PLACEHOLDER_ENABLED
              exit 1
              ;;
            *)
              echo You did not specified what to enable or this feature does not exist
              echo "$USAGE"
              exit 1
              ;;
        esac
        exit 1
        ;;
    '-d'|'--disable')
         case "$2" in
           'swg')
              disable_swgmaxdebug &&
              echo SWG Max debug logging has DISABLED
              exit 1
              ;;
           'kdf')
              echo KDF_PLACEHOLDER_DISABLED
              exit 1
              ;; 
            *)
              echo You did not specified what to disable or this feature does not exist
              echo "$USAGE"
              exit 1 
              ;;
        esac
        exit 1
        ;;
'-v'|'--verify')
         case "$2" in
           'swg')   
              verify_swgmaxdebug &&
              exit 1
              ;;
           'kdf')
              echo KDF_PLACEHOLDER_VERIFY
              exit 1
              ;;
            *)  
              echo You did not specified what to verify or this feature does not exist
              echo "$USAGE"
              exit 1
              ;;
        esac
        exit 1
        ;;
    '-h'|'--help')
        echo "$USAGE"
        exit 0
        ;;
    *)
        echo "$USAGE"
        exit 1
        ;;
esac

