#!/usr/bin/env bash


if test -f '/opt/cisco/anyconnect/umbrella/OrgInfo.json'; then
    BASE_DIR='/opt/cisco/anyconnect/umbrella'
    AC_BASE_DIR='/opt/cisco/anyconnect'
    CLIENT='anyconnect'
elif test -f '/opt/cisco/secureclient/umbrella/OrgInfo.json'; then
    BASE_DIR='/opt/cisco/secureclient/umbrella'
    AC_BASE_DIR='/opt/cisco/secureclient'
    CLIENT='secureclient'
else
    echo "You don't have either Anyconnnect or Secure Client installed"
    exit 1
fi

debug_flags=$3

read -r -d '' USAGE << EGASU
Usage: `basename $0` [-s|-e|-e swg|-e kdf|-d|-d swg|-d kdf|-l|-u|-r|-h]

    -s, --status      Print Anyconnect/Secure Client service status and types of logging enabled
    -e, --enable      Enable logging feature
        --enable swg  Enable SWG maximum debug logging
        --enable kdf 0xffffffff Enable KDF debug logging with debug flags set to 0xffffffff 
    -d, --disable     Disable logging feature
        --disable swg Disable SWG maximum debug logging
        --disable kdf Disable KDF debug logging
    -l, --load        Load/Register Anyconnect/Secure Client service
    -u, --unload      Unload/Unregister Anyconect/Secure Client service
    -r, --restart     Reload/Restart Umbrella Roaming Module
    -h, --help        Show this message.
EGASU

# Check status of the service
function check_status {
    acstatus=$(launchctl print system/com.cisco.$CLIENT.vpnagentd)
    if [[ $acstatus == *"state = running"* ]]; then
        echo "+ $CLIENT service is ENABLED and RUNNING"
    else
        echo "- $CLIENT service DISABLED"
    fi
}

# Stop service
function stop_service {
    sudo launchctl unload /Library/LaunchDaemons/com.cisco.$CLIENT.vpnagentd.plist
}

# Start service
function start_service {
    sudo launchctl load /Library/LaunchDaemons/com.cisco.$CLIENT.vpnagentd.plist
}

# Enable SWG Max debug logging
function enable_swgmaxdebug {
    sudo cat $BASE_DIR/SWG/SWGConfig.json | awk -F "orgConfig\": " '{print $2}' | awk -F ", \"commonConfig" '{print $1}' | sed "s/}/, \"logLevel\": \"1\" }/g" > $BASE_DIR/data/swg_org_config.flag
}

# Disable SWG Max Debug Logging
function disable_swgmaxdebug {
    sudo rm $BASE_DIR/data/swg_org_config.flag 
}

# Enable KDF logs
function enable_kdf {
    [ -z "$debug_flags" ] && echo "WARNING!!! Debug flags are empty, no KDF logging will be active"
    if [[ $CLIENT == "anyconnect" ]]; then
        echo debug=$debug_flags | sudo tee $AC_BASE_DIR/acsock.cfg
    elif [[ $CLIENT == "secureclient" ]]; then
        echo debug=$debug_flags | sudo tee $AC_BASE_DIR/kdf/acsock.cfg
    fi
}

# Disable KDF logs
function disable_kdf {
    sudo rm $AC_BASE_DIR/acsock.cfg
    sudo rm $AC_BASE_DIR/kdf/acsock.cfg
}

function verify_kdf {
    if test -f $AC_BASE_DIR/acsock.cfg; then
       echo "+ KDF debug flags file found"
    elif test -f $AC_BASE_DIR/kdf/acsock.cfg; then
        echo "+ KDF debug flags file found"
    else
       echo "- KDF debug flags file does not exist"
    fi
    if [[ $CLIENT == "anyconnect" ]]; then 
        kdflogout=$(log show --predicate 'subsystem contains "com.cisco.anyconnect.acsock"' --debug --info --last 5m)
    elif [[ $CLIENT == "secureclient" ]];then
        kdflogout=$(log show --predicate 'subsystem contains "com.cisco.anyconnect.acsock"' --debug --info --last 5m)
    fi
    if [[ $kdflogout == *"CSocketScanSafePluginImp::notify_recv"* ]]; then
        echo "+ Looks like KDF Logs enabled and we see web redirection events"
    else
        echo "- No events available, check if KDF logging is enabled"
    fi
    echo " "
    echo "You can run next command to manually verify if we see KDF logs:"
    echo "log show --predicate 'subsystem contains \"com.cisco.anyconnect.acsock\"' --debug --info --last 5m"
}

function verify_swgmaxdebug {
    if test -f $BASE_DIR/data/swg_org_config.flag; then
       echo "+ swg_org_config.flag found"
    else
       echo "- swg_org_config.flag does not exist"
    fi
    if [[ $CLIENT == "anyconnect" ]]; then 
        swglogout=$(log show --predicate 'subsystem contains "com.cisco.anyconnect.swg"||senderImagePath endswith "acswgagent"' --debug --info --last 5m)
    elif [[ $CLIENT == "secureclient" ]];then
        swglogout=$(log show --predicate 'subsystem contains "com.cisco.secureclient.swg"||senderImagePath endswith "csc_swgagent"' --debug --info --last 5m)
    fi
    if [[ $swglogout == *"Hostnames from KDF are"* ]]; then
        echo "+ Looks like SWG Max debug logging enabled and we see web redirection events"
    else
        echo "- No events available, check if SWG max debug logging is enabled"
    fi
    echo " "    
    echo "You can run next command to manually verify if we see SWG maximum debug logs:"
    if [[ $CLIENT == "anyconnect" ]]; then
        echo "log show --predicate 'subsystem contains \"com.cisco.anyconnect.swg\"||senderImagePath endswith \"acswgagent\"' --debug --info --last 5m"
    elif [[ $CLIENT == "secureclient" ]];then
        echo "log show --predicate 'subsystem contains \"com.cisco.secureclient.swg\"||senderImagePath endswith \"csc_swgagent\"' --debug --info --last 5m"
    fi
}

case "$1" in
    '-s'|'--status')
        verify_swgmaxdebug &&
        verify_kdf &&
        check_status
        exit 0
        ;;
    '-l'|'--load')
        start_service &&
        echo $CLIENT service has been STARTED. &&
        exit 0 ||
        echo ERROR: $CLIENT service can only be enabled if it has 
previously been disabled by this utility.
        exit 1
        ;;
    '-u'|'--unload')
        stop_service &&
        echo $CLIENT service has been STOPPED. ||
        echo ERROR: $CLIENT service does not appear to be enabled.
        exit 1
        ;;
    '-r'|'--restart')
        stop_service &&
        echo $CLIENT service has been STOPPED. &&
        start_service &&
        echo $CLIENT has been STARTED.
        exit 0
        ;;
    '-e'|'--enable')
        case "$2" in
           'swg')
              enable_swgmaxdebug &&
              echo "+ SWG Max debug logging has ENABLED"
              exit 1
              ;;
           'kdf')
              enable_kdf &&
              echo " + KDF logs has ENABLED"
              exit 1
              ;;
            *)
              echo You did not specified what to enable or this feature does not exist
              echo "$USAGE"
              exit 1
              ;;
        esac
        exit 1
        ;;
    '-d'|'--disable')
         case "$2" in
           'swg')
              disable_swgmaxdebug &&
              echo SWG Max debug logging has DISABLED
              exit 1
              ;;
           'kdf')
              disable_kdf &&
              echo "+ KDF logs has DISABLED"
              exit 1
              ;; 
            *)
              echo You did not specified what to disable or this feature does not exist
              echo "$USAGE"
              exit 1 
              ;;
        esac
        exit 1
        ;;
'-v'|'--verify')
         case "$2" in
           'swg')   
              verify_swgmaxdebug &&
              exit 1
              ;;
           'kdf')
              verify_kdf &&
              exit 1
              ;;
            *)  
              echo You did not specified what to verify or this feature does not exist
              echo "$USAGE"
              exit 1
              ;;
        esac
        exit 1
        ;;
    '-h'|'--help')
        echo "$USAGE"
        exit 0
        ;;
    *)
        echo "$USAGE"
        exit 1
        ;;
esac

